version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
    
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sorteodwb-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/sorteodb
      - PORT=3000

volumes:
  mongo_data:
